courses/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.course_overview.as_view(), name='course_overview'),

    path('add/',
         views.course_add, name="course_add"),

    path('edit_course/<int:course_id>',
         views.course_edit, name='course_edit'),

    path('delete_course/<int:course_id>',
         views.course_delete, name='course_delete'),

    path('<slug:slug>/',
         views.course_detail, name='course_detail'),

    # Lesson Urls
    path('<slug:course_slug>/add_lesson/',
         views.lesson_add, name="lesson_add"),

    path('<slug:course_slug>/<slug:lesson_slug>/',
         views.lesson_detail, name='lesson_detail'),

    path('<slug:course_slug>/<slug:lesson_slug>/edit/',
         views.lesson_edit, name='lesson_edit'),

    path('<slug:course_slug>/delete/<int:lesson_id>/',
         views.lesson_delete, name='lesson_delete'),
]

gong_fu_courses/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home_view
from contact import views as contact_view
from courses import views as course_views

urlpatterns = [
    path("", include("home.urls"), name="home-urls"),
    path("custom/", include("custom_pages.urls"), name="custom-pages-urls"),
    path("courses/", include("courses.urls"), name="courses-urls"),
    path("contact/", include("contact.urls"), name="contact-urls"),
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
]

handler404 = 'custom_pages.views.custom_404'

home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='home'),
]

courses/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

LEVEL = ((0, "Foundation"), (1, "Intermediate"), (2, "Advanced"))
CATEGORY = (
    (0, "Basics"),
    (1, "Qigong"),
    (2, "Taiji"),
    (3, "Bagua"),
    (4, "Taiyi"),
    (5, "Sword"),
    (6, "Gun")
)


class Course(models.Model):
    """
    Model representing a course.

    Attributes:
        title (str): The title of the course.
        slug (str): The slug of the course.
        description (str): The description of the course.
        category (int): The category of the course.
        featured_image (CloudinaryField): The featured image of the course.
        content (str): The content of the course.
        level (int): The level of the course.
        created_on (datetime): The datetime when the course was created.
        updated_on (datetime): The datetime when the course was last updated.
        order (int): The order of the course.
    """

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()
    category = models.IntegerField(choices=CATEGORY, default=0)
    featured_image = CloudinaryField('image', default='placeholder')
    content = models.TextField()
    level = models.IntegerField(choices=LEVEL, default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    order = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        ordering = ["order"]


class Lesson(models.Model):
    """
    Model representing a lesson.

    Attributes:
        course (Course): The course to which the lesson belongs.
        title (str): The title of the lesson.
        slug (str): The slug of the lesson.
        video_url (str): The URL of the video for the lesson.
        description (str): The description of the lesson.
        recommendation (str): Recommendations for the lesson.
        created_on (datetime): The datetime when the lesson was created.
        order (int): The order of the lesson.
    """

    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="lessons"
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    video_url = models.URLField(max_length=200, blank=True, null=True, default="https://www.youtube.com/embed/ji7J3GwhfdU?si=aGjz83D0b7bqvMQj")
    description = models.TextField(blank=True, null=True)
    recommendation = models.TextField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    order = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.course} - {self.title}"
    
    class Meta:
        ordering = ["order"]

courses/forms.py
from .models import Course, Lesson
from django import forms


class CourseForm(forms.ModelForm):
    """
    Form for creating and updating Course objects.

    Attributes:
        title (str): The title of the course.
        slug (str): The slug of the course.
        description (str): The description of the course.
        category (int): The category of the course.
        featured_image (str): The URL of the featured image for the course.
        content (str): The content of the course.
        level (int): The level of the course.
        order (int): The order of the course.
    """

    class Meta:
        model = Course
        fields = (
            'title', 'slug', 'description',
            'category', 'featured_image', 'content', 'level', 'order')

        error_messages = {
            '__all__': {
                'required': "This field is required. LOL",
            },
        }


class LessonForm(forms.ModelForm):
    """
    Form for creating and updating Lesson objects.

    Attributes:
        title (str): The title of the lesson.
        slug (str): The slug of the lesson.
        video_url (str): The URL of the video for the lesson.
        description (str): The description of the lesson.
        recommendation (str): Recommendations for the lesson.
        order (int): The order of the lesson.
    """

    class Meta:
        model = Lesson
        fields = (
            'title', 'slug', 'video_url',
            'description', 'recommendation', 'order')

        labels = {
            "video_url": "Video Url - Must be embed link"
        }

courses/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic
from .models import Course, Lesson
from .forms import CourseForm, LessonForm
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from custom_pages.views import user_has_permission, user_is_superuser, access_denied


# Create your views here.
class course_overview(generic.ListView):
    """
    View for displaying an overview of all courses.

    Attributes:
        queryset: Queryset of all Course objects.
        template_name: The name of the template used for rendering the view.
    """
    queryset = Course.objects.all()
    template_name = "course_overview.html"
    paginate_by = 8


@login_required
def course_detail(request, slug):
    """
    View for displaying details of a specific course.

    Args:
        request (HttpRequest): The HTTP request object.
        slug (str): The slug of the course.

    Returns:
        HttpResponse: Rendered course detail template.

    Raises:
        Http404: If the requested course does not exist.
    """
    if user_has_permission(request.user):
        queryset = Course.objects.all()
        course = get_object_or_404(queryset, slug=slug)
        lessons = course.lessons.all()

        return render(
            request,
            "course_detail.html",
            {
                "course": course,
                "lessons": lessons,
            }
        )
    else:
        return access_denied(request)


@login_required
def course_add(request):
    """
    View for adding a new course.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: Rendered course add template.
    """
    if user_is_superuser(request.user):
        # Handle the POST request from the course form
        if request.method == "POST":
            course_form = CourseForm(data=request.POST, files=request.FILES)
            if course_form.is_valid():
                course = course_form.save(commit=False)
                course.save()
                # Display success message
                messages.add_message(
                    request, messages.SUCCESS,
                    'Course successfully added'
                )
                return redirect('course_overview')
            else:
                messages.add_message(
                    request, messages.ERROR,
                    'Form not valid'
                )
        else:
            course_form = CourseForm()

        return render(
            request,
            "course_add.html",
            {
                "course_form": course_form,
            }
        )
    else:
        return access_denied(request)


@login_required
def course_edit(request, course_id):
    """
    View for editing an existing course.

    Args:
        request (HttpRequest): The HTTP request object.
        course_id (int): The ID of the course to be edited.

    Returns:
        HttpResponse: Rendered course edit template.

    Raises:
        Http404: If the requested course does not exist.
    """
    if user_is_superuser(request.user):
        course = get_object_or_404(Course, pk=course_id)
        if request.method == "POST":
            course_form = CourseForm(
                data=request.POST,
                files=request.FILES,
                instance=course)

            if course_form.is_valid():
                course_form.save()
                messages.add_message(
                    request, messages.SUCCESS, 'Course Updated!')

                return HttpResponseRedirect(reverse('course_overview'))
            else:
                messages.add_message(
                    request, messages.ERROR, 'Error updating course!')
        else:
            # If it's a GET request, initialize the form with the instance data
            course_form = CourseForm(instance=course)

        return render(
            request, 'course_edit.html',
            {'course_edit_form': course_form, 'course': course})

    else:
        return access_denied(request)


@login_required
def course_delete(request, course_id):
    """
    View for deleting an existing course.

    Args:
        request (HttpRequest): The HTTP request object.
        course_id (int): The ID of the course to be deleted.

    Returns:
        HttpResponseRedirect: Redirects to the course overview page.

    Raises:
        Http404: If the requested course does not exist.
    """
    if user_is_superuser(request.user):
        course = get_object_or_404(Course, pk=course_id)
        if request.method == "POST":
            course.delete()
            messages.add_message(request, messages.SUCCESS, 'Course deleted!')
            return HttpResponseRedirect(reverse('course_overview'))
        else:
            return render(
                request,
                'course_delete.html',
                {'course': course})

    else:
        return access_denied(request)


@login_required
def lesson_detail(request, course_slug, lesson_slug):
    """
    View for displaying details of a specific lesson.

    Args:
        request (HttpRequest): The HTTP request object.
        course_slug (str): The slug of the course to which the lesson belongs.
        lesson_slug (str): The slug of the lesson.

    Returns:
        HttpResponse: Rendered lesson detail template.

    Raises:
        Http404: If the requested course or lesson does not exist.
    """
    if user_has_permission(request.user):
        course = get_object_or_404(Course, slug=course_slug)
        lesson = get_object_or_404(Lesson, slug=lesson_slug, course=course)
        return render(
            request,
            'lesson_detail.html',
            {
                'lesson': lesson,
                'course': course
            })
    else:
        return access_denied(request)


@login_required
def lesson_add(request, course_slug):
    """
    View for adding a new lesson to a course.

    Args:
        request (HttpRequest): The HTTP request object.
        course_slug (str): The slug of the course

    Returns:
        HttpResponse: Rendered lesson add template.
    """
    if user_is_superuser(request.user):
        course = get_object_or_404(Course, slug=course_slug)

        if request.method == "POST":
            lesson_form = LessonForm(data=request.POST)
            if lesson_form.is_valid():
                lesson = lesson_form.save(commit=False)
                lesson.course = course
                lesson.save()
                messages.add_message(
                    request, messages.SUCCESS,
                    'Lesson successfully added'
                )
                return redirect('course_detail', slug=course_slug)
        else:
            lesson_form = LessonForm()

        return render(
            request,
            "lesson_add.html",  # Ensure the template path is correct
            {
                "lesson_form": lesson_form,
                "course": course,
            }
        )
    else:
        return access_denied(request)


@login_required
def lesson_edit(request, course_slug, lesson_slug):
    """
    View for editing an existing lesson.

    Args:
        request (HttpRequest): The HTTP request object.
        course_slug (str): The slug of the course to which the lesson belongs.
        lesson_slug (str): The slug of the lesson to be edited.

    Returns:
        HttpResponse: Rendered lesson edit template.

    Raises:
        Http404: If the requested course or lesson does not exist.
    """
    if user_is_superuser(request.user):
        course = get_object_or_404(Course, slug=course_slug)
        lesson = get_object_or_404(Lesson, slug=lesson_slug, course=course)

        if request.method == "POST":
            lesson_form = LessonForm(data=request.POST, instance=lesson)
            if lesson_form.is_valid():
                lesson_form.save()
                messages.add_message(
                    request, messages.SUCCESS,
                    'Lesson successfully updated'
                )
                return redirect('course_detail', slug=course_slug)

        else:
            lesson_form = LessonForm(instance=lesson)

        return render(
            request,
            'lesson_edit.html',
            {
                'lesson_form': lesson_form,
                'course': course,
                'lesson': lesson
            }
        )
    else:
        return access_denied(request)


@login_required
def lesson_delete(request, lesson_id, course_slug):
    """
    View for deleting an existing lesson.

    Args:
        request (HttpRequest): The HTTP request object.
        lesson_id (int): The ID of the lesson to be deleted.
        course_slug (str): The slug of the course

    Returns:
        HttpResponseRedirect: Redirects to the course detail page.

    Raises:
        Http404: If the requested lesson does not exist.
    """
    if user_is_superuser(request.user):
        course = get_object_or_404(Course, slug=course_slug)
        lesson = get_object_or_404(Lesson, pk=lesson_id)
        if request.method == "POST":
            lesson.delete()
            messages.add_message(request, messages.SUCCESS, 'Lesson deleted!')
            return redirect('course_detail', slug=course_slug)
        else:
            return render(
                request,
                'lesson_delete.html',
                {
                    'lesson': lesson,
                    'course': course
                }
            )
    else:
        return access_denied(request)

courses/templates/course_add.html
{% extends 'base.html' %} 
{% block content %}
{% load crispy_forms_tags %}

<div class="container-fluid">
    <!-- Title Row -->
    <div class="row text-center mt-5">
        <div class="col-md-12">
            <h1 class="title-1">Add New Course</h1>
        </div>
    </div>
    
    <!-- Form Row -->
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8">
            <!-- Course Form -->
            <form id="courseForm" method="post" class="form" enctype="multipart/form-data">
                {{ course_form | crispy }} <!-- Render form with crispy forms -->
                {% csrf_token %} <!-- CSRF token for security -->
                <button id="submitButton" type="submit"
                class="btn-warrior btn-warrior-color-green">Submit</button> <!-- Submit Button -->
                <a href="{% url 'course_overview' %}" id="cancleButton"
                class="btn-warrior btn-warrior-color-grey">Cancle</a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

courses/templates/course_delete.html
{% extends 'base.html' %} 
{% block content %}
{% load crispy_forms_tags %}

<div class="container-fluid">
    <div class="row text-center mt-5">
        <div class="col-md-12">
            <!-- Title displaying the course ID being edited -->
            <h1 class="title-1">Confirm Course Deletion</h1>
        </div>
    </div>
    <div class="row justify-content-center text-center">
        <div class="col-sm-12 col-md-8">
            <!-- Form for deleting the course -->
            <form id="courseDeleteForm" method="post">
                {% csrf_token %} <!-- CSRF_ALLOWED_HOSTS -->
                <p>Are you sure, you want to delete the course 
                    <span style="font-weight: bold">"{{course.title}}"</span>?
                    <br>
                    All lessons within this course will be deleted as well. This can not be undone.
                </p>
                <!-- Submit button for the form -->
                <button id="submitButton" type="submit"
                class="btn-warrior btn-warrior-color-red">Delete</button>
                <a href="{% url 'course_overview' %}" id="cancleButton"
                class="btn-warrior btn-warrior-color-grey">Cancle</a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

courses/templates/course_detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 p-0">
            <div class="course-banner-container">
                {% if "placeholder" in course.featured_image.url %}
                    <!-- Display default image if no featured image is set -->
                    <img class="course-banner" src="{% static 'images/default-course-image.jpg' %}" alt="{{ course.title }} Banner">
                    <div class="course-title-overlay">
                        <h1 class="title-1">{{ course.title }}</h1>
                    </div>
                {% else %}
                    <!-- Display course's featured image -->
                    <img class="course-banner" src="{{ course.featured_image.url }}" alt="{{ course.title }}">
                    <div class="course-title-overlay">
                        <h1 class="title-1">{{ course.title }}</h1>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container-fluid px-5">
    <!-- Description section -->
    <div class="row mt-3">
        <div class="col-md-12">
            <h2 class="title-2">Description</h2>
            <p class="lead">
                {{ course.description  |safe }}
            </p>
        </div>
    </div>
    
    <!-- Content section -->
    <div class="row mt-3">
        <div class="col-md-12">
            <h2 class="title-2">Content</h2>
            <p class="lead">
                {{ course.content | safe }}
            </p>
        </div>
    </div>
    
</div>

<!-- LESSONS / COURSE CURRICULUM -->
<div class="container-fluid px-5 mt-5">
    {% if user.is_superuser %}
    <div class="row mb-3">
        <div class="col-md-12">
            <!-- Button to add a new lesson -->
            <a href="{% url 'lesson_add' course.slug %}" class="btn-warrior btn-warrior-color-green"><i class="fas fa-plus"></i> new Lesson</a>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-md-12">
            <span class="title-2">Course Curriculum</span>
        </div>
    </div>
    <div class="row mt-3 mb-5">
        <div class="col-md-12">
            {% for lesson in lessons %}
                <div class="row">
                    <div class="col-md-12 bg-grey p-2 d-flex justify-content-between align-items-center
                        {% if forloop.first %} border-radius-top{% endif %}
                        {% if forloop.last %} border-radius-bottom{% endif %}">
                        <div class="padding-left-1_5">
                            <i class="fas fa-file"></i> 
                            <!-- Link to the lesson -->
                            <a href="{{ lesson.slug }}" class="lesson-link">{{ lesson.title }}</a>
                        </div>
                        <div class="padding-right-1_5">
                            <!-- Button to start the lesson -->
                            <a href="{{ lesson.slug }}" class="btn-warrior btn-warrior-color-blue" title="Start Lesson">
                                <i class="fas fa-play start-icon"></i>
                            </a>
                            {% if user.is_superuser %}
                            <!-- Button to edit the lesson -->
                            <a href="{% url 'lesson_edit' course.slug lesson.slug %}" class="btn-warrior btn-warrior-color-yellow btn-edit" title="Edit Lesson">
                                <i class="fas fa-edit"></i>
                            </a>
                            <!-- Button to delete the lesson -->
                            <a href="{% url 'lesson_delete' course.slug lesson.id %}" class="btn-warrior btn-warrior-color-red btn-delete-lesson" title="Delete Lesson">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                            {% endif %}
                        </div>
                    </div>
                    {% if not forloop.last %}
                        <hr style="margin-bottom: 0px;">
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

courses/templates/course_edit.html
{% extends 'base.html' %} 
{% block content %}
{% load crispy_forms_tags %}

<div class="container-fluid">
    <div class="row text-center mt-5">
        <div class="col-md-12">
            <!-- Title displaying the course ID being edited -->
            <h1 class="title-1">EDIT COURSE</h1>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8">
            <!-- Form for editing the course -->
            <form id="courseEditForm" method="post" class="form" enctype="multipart/form-data">
                <!-- Render the course edit form using crispy forms -->
                {{ course_edit_form | crispy }}
                <!-- CSRF token for security -->
                {% csrf_token %} <!-- CSRF_ALLOWED_HOSTS -->
                <!-- Submit button for the form -->
                <button id="submitButton" type="submit"
                class="btn-warrior btn-warrior-color-green">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

courses/templates/course_overview.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Content starts here -->
<!-- Display 'Add New Course' button only for superuser -->
{% if user.is_superuser %}
<div class="container-fluid mt-3 mb-3">
    <div class="row">
        <div class="col-md-12">
            <a href="{% url 'course_add' %}" class="btn-warrior btn-warrior-color-green">
                <i class="fas fa-plus"></i> new course
            </a>
        </div>
    </div>
</div>
{% endif %}

<div class="container-fluid">

    <!-- Course overview title -->
    <h1>COURSE OVERVIEW</h1>

    <div class="row">
        <!-- Loop through each course in the paginated course list -->
        {% for course in page_obj %}
        <div class="col-xs-12 col-sm-6 col-md-3 mt-3 mb-3">
            <div class="card border-style-1">
                <!-- Course link and featured image -->
                <a href='{{ course.slug }}'>
                    {% if "placeholder" in course.featured_image.url %}
                        <img class="card-img-top" src="{% static 'images/default-course-image.jpg' %}" alt="{{ course.title }} Banner">
                    {% else %}
                        <img class="card-img-top" src="{{ course.featured_image.url }}" alt="{{ course.title }}">
                    {% endif %}
                </a>
                <!-- Display course level with corresponding background color -->
                {% if course.get_level_display == "Foundation" %}
                    <div class='course-level bg-foundation'>{{ course.get_level_display }}</div>
                {% elif course.get_level_display == "Intermediate" %}
                    <div class='course-level bg-intermediate'>{{ course.get_level_display }}</div>
                {% else %}
                    <div class='course-level bg-advanced'>{{ course.get_level_display }}</div>
                {% endif %}
                <div class='card-header'>
                    <a href='{{ course.slug }}' class='card-title-link'>
                        <h2 class='card-title'>{{ course.title }}</h2>
                    </a>
                </div>
                <div class='card-body'>
                    <p class='card-text'>{{ course.description }}</p>
                </div>
                <div class='card-footer'>
                    <div class="row">
                        <div class="col-md-12 d-flex justify-content-between">
                            <!-- 'Let's Go' button to start the course -->
                            <a href='{{ course.slug }}' class='btn-warrior btn-warrior-color-blue'>let's go</a>
                            <!-- Superuser options: Edit and Delete buttons -->
                            {% if user.is_superuser %}
                                <div class="ml-1">
                                    <!-- Edit Course -->
                                    <a href='edit_course/{{ course.id }}' class='btn-warrior btn-warrior-color-yellow ml-1 btn-edit' title="Edit Course">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <!-- Delete Course -->
                                    <a href='delete_course/{{ course.id }}' class='btn-warrior btn-warrior-color-red btn-delete-course' title="Delete Course">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                    {% comment %} <button class="btn-warrior btn-warrior-color-red btn-delete-course" title="Delete Course" course_id="{{ course.id }}">
                                        <i class="fas fa-trash-alt"></i>
                                    </button> {% endcomment %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <hr class="hr-warrior">
    
    <!-- Pagination controls -->
    <div class="pagination">
        <div class="block-1">
            <!-- If there is a previous page, show the first and previous links -->
            {% if page_obj.has_previous %}
                <a href="?page=1" class="btn-warrior btn-warrior-color-blue">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="btn-warrior btn-warrior-color-blue">previous</a>
            {% endif %}
        </div>
        <div class="block-2">
            <!-- Display the current page number and total pages -->
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
        </div>
        <div class="block-3">
            <!-- If there is a next page, show the next and last links -->
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="btn-warrior btn-warrior-color-blue">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="btn-warrior btn-warrior-color-blue">last &raquo;</a>
            {% endif %}
        </div>
    </div>
</div>
<!-- Content ends here -->
{% endblock content %}

courses/templates/lesson_add.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container-fluid back-to-course-navbar">
    <a href="{% url 'course_detail' course.slug %}" class="warrior-url">&laquo; back to {{ course.title }}</a>
</div>

<div class="container-fluid">
    <!-- Header row with title -->
    <div class="row text-center mt-5">
        <div class="col-md-12">
            <h1 class="title-1">Add New Lesson</h1>
        </div>
    </div>
    
    <!-- Form row for adding a new lesson -->
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8">
            <!-- Lesson form with CSRF protection -->
            <form id="lessonForm" method="post" class="form">
                <!-- Render the lesson form using crispy forms for better styling -->
                {{ lesson_form | crispy }}
                <!-- CSRF token for security -->
                {% csrf_token %}
                <!-- Submit button -->
                <button id="submitButton" type="submit" class="btn-warrior btn-warrior-color-green">Submit</button>
                <a href="{% url 'course_detail' course.slug %}" id="cancleButton"
                class="btn-warrior btn-warrior-color-grey">Cancle</a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

courses/templates/lesson_delete.html
{% extends 'base.html' %} 
{% block content %}
{% load crispy_forms_tags %}

<div class="container-fluid">
    <div class="row text-center mt-5">
        <div class="col-md-12">
            <!-- Title displaying the course ID being edited -->
            <h1 class="title-1">Confirm Lesson Deletion</h1>
        </div>
    </div>
    <div class="row justify-content-center text-center">
        <div class="col-sm-12 col-md-8">
            <!-- Form for deleting the course -->
            <form id="courseDeleteForm" method="post">
                {% csrf_token %} <!-- CSRF_ALLOWED_HOSTS -->
                <p>Are you sure, you want to delete the lesson 
                    <span style="font-weight: bold">"{{lesson.title}}"</span>?
                    <br>This can not be undone.
                </p>
                <!-- Submit button for the form -->
                <button id="submitButton" type="submit"
                class="btn-warrior btn-warrior-color-red">Delete</button>
                <a href="{% url 'course_detail' course.slug %}" id="cancleButton"
                class="btn-warrior btn-warrior-color-grey">Cancle</a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}